package com.github.giovaneneves7.travellingsalesmanproblem.widgets;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.Timer;

/**
 *
 * @author Giovane Neves
 */
public class ScreenBackground extends javax.swing.JPanel {

    /**
     * The population generation number.
     */
    private final AtomicInteger generation;
    
    /**
     * Creates new form ScreenBackground
     */
    public ScreenBackground() {
        initComponents();
        this.generation = new AtomicInteger(0);
        // Repaints the screen every 5 milliseconds
        Timer timer = new Timer(5, (e) -> {
            repaint();
        });
        timer.start();
    }
    
    @Override
    public void paintComponent(final Graphics graphics){
        
        super.paintComponent(graphics);
        final Graphics2D g = (Graphics2D) graphics;
        g.setColor(Color.CYAN);
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g.drawString("Generation: ".concat(String.valueOf(this.generation.incrementAndGet())), 350, 15);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
